# Generated by Django 3.0.3 on 2020-05-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinehistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicinehistory',
            name='name',
        ),
        migrations.AddField(
            model_name='medicinehistory',
            name='medicine_id',
            field=models.IntegerField(default=0),
        ),
    ]
