# Generated by Django 3.0.3 on 2020-05-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_history', '0002_auto_20200513_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinehistory',
            name='time',
        ),
        migrations.AddField(
            model_name='medicinehistory',
            name='date',
            field=models.DateField(default='2020-04-18'),
            preserve_default=False,
        ),
    ]
