export const GET_MEDICINE = "GET_MEDICINE";
export const DELETE_MEDICINE = "DELETE_MEDICINE";
export const ADD_MEDICINE = "ADD_MEDICINE";
export const UPDATE_MEDICINE = "UPDATE_MEDICINE";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_MEDICINE_HISTORY = "GET_MEDICINE_HISTORY";
export const ADD_MEDICINE_HISTORY = "ADD_MEDICINE_HISTORY";