# Generated by Django 2.2.5 on 2021-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='drawer',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
